name: Context Examples

on: [push]

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "My Step"
              run: 
                echo "Action!!! $MY_ACTION"
                echo "Actor!!! $MY_ACTOR"
                echo "Event!!! $MY_EVENT"
              env:
                MY_ACTION: ${{github.action}}
                MY_ACTOR: ${{github.actor}}
                MY_EVENT:  ${{github.event_name}}