name: "Dep Jobs Examples"

on: [push]

jobs:
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
          - name: "Step A"
            run: echo "World!!"
    job1:
        runs-on: ubuntu-latest
        steps:
           - name: "Step B"
             run: echo "Hello"