name: "Workflow Commands"

on: ['push']

jobs:
    my-job:
        runs-on: ubuntu-lastest
        steps:
           - name: "group logging"
             run: 
                echo "::group::My Groupd Message"
                echo "Msg 1"
                echo "Msg 2"
                echo "::endgroup::"